#FROM nginx
FROM owasp/modsecurity:3

#RUN sudo unlink /etc/nginx/sites-enabled/default
#RUN cd etc/nginx/sites-available/

#COPY reverse-proxy.conf etc/nginx/sites-available/

#RUN sudo ln -s /etc/nginx/sites-available/reverse-proxy.conf /etc/nginx/sites-enabled/reverse-proxy.conf

